//! Autogenerated weights for pallet_numail
//!
//! PHASE 9: Worst-case weight estimates based on enhanced benchmarks.
//! These are *estimates* — run `cargo benchmark --package pallet-numail --features runtime-benchmarks`
//! on your target hardware to replace with actual profiled values.
//!
//! Weight calculation rationale:
//! - RocksDB read: ~25 µs, write: ~100 µs per the typical Substrate baseline
//! - `send_mail` (heaviest): max 16 recipients → 16 mailbox reads + 16 policy checks + 
//!   max 8 attachments → 8 anchor checks + 1 envelope write + 16 delivery state writes + 
//!   16 index writes = ~50 DB ops total → ~5ms base + policy/attachment overhead
//! - `system_notice`: similar to send_mail but skips policies → slightly lower
//! - `block_sender` (worst): blocklist nearly full (63/64) → search cost on insert
//! - `unblock_sender` (worst): blocklist full → O(n) filter across 64 entries
//! - Others: minimal variance, dominated by 1-2 DB ops

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_numail.
pub trait WeightInfo {
	fn create_mailbox() -> Weight;
	fn send_mail() -> Weight;
	fn mark_read() -> Weight;
	fn tombstone() -> Weight;
	fn move_to_folder() -> Weight;
	fn set_mailbox_policy() -> Weight;
	fn block_sender() -> Weight;
	fn unblock_sender() -> Weight;
	fn system_notice() -> Weight;
}

/// Weights for pallet_numail using the Substrate node and recommended hardware.
/// These are worst-case estimates; actual values depend on your benchmark hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Worst case: max folders (16) declared.
	/// - 1 read (contains check on Mailboxes)
	/// - 1 write (insert MailboxConfig)
	/// Storage: O(n) where n = number of folders (bounded to 16)
	fn create_mailbox() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Worst case: max recipients (16) + max attachments (8) + encrypted body + encrypted keys.
	/// - 16 reads (Mailboxes for each recipient's policy check)
	/// - 1 write (MailItems envelope)
	/// - 16 reads + 16 writes (DeliveryState per recipient)
	/// - 16 MailboxIndex mutations
	/// - 16 writes (MailEncryptedKeys for each recipient)
	/// - 1 NextMailId read + write
	/// Total: ~52 DB operations + policy overhead + encryption data storage
	fn send_mail() -> Weight {
		Weight::from_parts(180_000_000, 0)  // Increased from 150M due to encrypted key storage
			.saturating_add(T::DbWeight::get().reads(34_u64))
			.saturating_add(T::DbWeight::get().writes(50_u64))  // +16 for MailEncryptedKeys
	}

	/// State transition: Delivered → Read.
	/// - 1 read (DeliveryState get)
	/// - 1 write (DeliveryState insert)
	/// - 1 PostageEscrow take (if postage was lodged)
	/// - 1 MailItems read (for envelope.sender, for postage release)
	/// - Postage release call (external trait, negligible cost)
	fn mark_read() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Remove content reference (index + state transition).
	/// - 1 read (DeliveryState get)
	/// - 1 read (MailFolderOf get, defensive fallback)
	/// - 1 read (MailboxIndex get old folder)
	/// - 1 write (MailboxIndex mutate, retain on vec)
	/// - 1 write (DeliveryState insert, new Tombstoned)
	fn tombstone() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Reindex mail: remove from old folder, add to new.
	/// - 1 read (DeliveryState get)
	/// - 1 read (MailFolderOf get old folder)
	/// - 1 read (MailboxIndex get old folder)
	/// - 1 write (MailboxIndex mutate old, retain)
	/// - 1 write (MailboxIndex try_mutate new, push)
	/// - 1 write (MailFolderOf insert new)
	fn move_to_folder() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Simple storage update: acceptance policy + retention window.
	/// - 1 read (Mailboxes try_mutate)
	/// - 1 write (Mailboxes update)
	fn set_mailbox_policy() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Worst case: blocklist nearly full (63/64 entries).
	/// - 1 read (Mailboxes contains_key)
	/// - 1 read (Blocklists get for try_mutate)
	/// - 1 write (Blocklists try_push, linear search on contains)
	/// - O(n) work where n = 63 (vec contains check)
	fn block_sender() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Worst case: blocklist full (64 entries), unblock first entry.
	/// - 1 read (Mailboxes contains_key)
	/// - 1 read (Blocklists get)
	/// - 1 write (Blocklists retain, O(n) filter across all 64)
	fn unblock_sender() -> Weight {
		Weight::from_parts(22_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Worst case: max recipients (16), system notice pathway (no policy checks).
	/// - 16 reads (Mailboxes contains_key for each recipient)
	/// - 1 write (MailItems envelope)
	/// - 16 reads + 16 writes (DeliveryState per recipient)
	/// - 16 MailboxIndex mutations
	/// - 1 NextMailId read + write
	/// Total: ~48 DB operations (slightly less than send_mail since no policy overhead)
	fn system_notice() -> Weight {
		Weight::from_parts(130_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(32_u64))
			.saturating_add(T::DbWeight::get().writes(32_u64))
	}
}

// For backwards compatibility and tests (unit testing doesn't use hardware timers).
impl WeightInfo for () {
	fn create_mailbox() -> Weight {
		Weight::from_parts(20_000_000, 0)
	}
	fn send_mail() -> Weight {
		Weight::from_parts(150_000_000, 0)
	}
	fn mark_read() -> Weight {
		Weight::from_parts(18_000_000, 0)
	}
	fn tombstone() -> Weight {
		Weight::from_parts(18_000_000, 0)
	}
	fn move_to_folder() -> Weight {
		Weight::from_parts(20_000_000, 0)
	}
	fn set_mailbox_policy() -> Weight {
		Weight::from_parts(12_000_000, 0)
	}
	fn block_sender() -> Weight {
		Weight::from_parts(18_000_000, 0)
	}
	fn unblock_sender() -> Weight {
		Weight::from_parts(22_000_000, 0)
	}
	fn system_notice() -> Weight {
		Weight::from_parts(130_000_000, 0)
	}
}